
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:shop
#    url: jdbc:h2:file:./shop;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  port: 8077