spring:
  application:
    name: point-shop
  config:
    import:
      - email.properties
      - sns.properties
  main:
    allow-bean-definition-overriding: true
  ##############################################
  #  Springboot Mail
  ############################################
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.spring.mail.username}
    password: ${email.spring.mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${sns.google.client-id}
            client-secret: ${sns.google.password}
          naver:
            client-id: ${sns.naver.client-id}
            client-secret: ${sns.naver.password}
            scope: name,email,profile_image
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  flyway:
    baseline-on-migrate: true
###########################################
# JWT
###########################################
jwt:
  header: Authorization
  secret: S6+e2uRDda0TTkxK95PUPmoLMKVF5tEo4GEjIYvi3hrAyR0srfDBZ1U/PNFKG37cmn++p/JGDSKhjCFXjPddzzuL9fbIXH2mGR6BI1P6UiY=
  token-validity-in-seconds: 86400