version: "3.7" # 파일 규격 버전
volumes:
  point-shop-dbdata: # 볼륨 명칭 : docker_dbdate
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  point-shop-db: # 서비스 명
    #### mysql 이미지
    image: mysql:8.0 # flyway 최신 버전이 Mysql 5.x 버전을 지원을 안해서 버전 업
    restart: always
    container_name: point-shop-mysql # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MYSQL_DATABASE=shopdb
      - MYSQL_USER=myshop
      - MYSQL_PASSWORD=point
      - MYSQL_ROOT_PASSWORD=1234  # MYSQL 루트 패스워드 설정 옵션
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - point-shop-dbdata:/var/lib/mysql2 # -v 옵션 (다렉토리 마운트 설정)